Feature/json metadata
fivetran/dbt_stripe pull request #51
Opened 2022-11-16 00:02 UTC by fivetran-reneeli

Pull Request
**Are you a current Fivetran customer?** 

internal
**What change(s) does this PR introduce?** 

update readme to include how to use metadata variable dictionary arguments 
**Did you update the CHANGELOG?** 

- [x] Yes

**Does this PR introduce a breaking change?**

- [ ] Yes (please provide breaking change details below.)
- [x] No  (please provide an explanation as to how the change is non-breaking below.)
updating readme only
**Did you update the dbt_project.yml files with the version upgrade (please leverage standard semantic versioning)? (In both your main project and integration_tests)** 

- [x] Yes

**Is this PR in response to a previously created Bug or Feature Request**

- [x] Yes, Issue/Feature https://github.com/fivetran/dbt_stripe/issues/45
- [ ] No 

**How did you test the PR changes?** 

 

- [ ] CircleCi  
- [x] Local (please provide additional testing details below)

**Select which warehouse(s) were used to test the PR**
 

- [x] BigQuery
- [x] Redshift
- [x] Snowflake
- [x] Postgres
- [ ] Databricks
- [ ] Other (provide details below)

**Provide an emoji that best describes your current mood**
 
:dancer:

**Feedback**

We are so excited you decided to contribute to the Fivetran community dbt package! We continue to work to improve the packages and would greatly appreciate your [feedback](https://www.surveymonkey.com/r/DQ7K7WW) on our existing dbt packages or what you'd like to see next.

2022-11-16 23:35 UTC, fivetran-joemarkiewicz requested changes
@fivetran-reneeli I just have a few comments below that should be updated before we are good to go

2022-11-16 23:35 UTC, fivetran-joemarkiewicz commented on README.md
> +If you happen to be using a reserved word as a field in your metadata, similarly incompatible name, or just wish to rename your field, we have updated our variables to be able to accept a dictionary
Once this is rolled out the customer will not be able to control the fivetran_utils version. We can probably remove the last line in this sentence.

2022-11-16 23:35 UTC, fivetran-joemarkiewicz commented on README.md
> +```
This isn't needed since the version of Fivetran Utils will already be handled for them

2022-11-16 23:35 UTC, fivetran-joemarkiewicz commented on integration_tests/dbt_project.yml
> -name: 'stripe_integration_tests'
Why was this removed?

2022-11-21 17:24 UTC, fivetran-reneeli commented on README.md
> +If you happen to be using a reserved word as a field in your metadata, similarly incompatible name, or just wish to rename your field, we have updated our variables to be able to accept a dictionary
updated

2022-11-21 17:24 UTC, fivetran-reneeli commented on README.md
> +```
updated

2022-11-21 22:59 UTC, fivetran-reneeli commented
@fivetran-joemarkiewicz  ready for re review

2022-11-21 23:21 UTC, fivetran-reneeli commented
@fivetran-joemarkiewicz  ready for review!

2022-11-23 03:27 UTC, fivetran-joemarkiewicz approved these changes
@fivetran-reneeli the condensed update looks great. I did have one last suggestion I would like for you to apply to the README before merging. Let me know if you have any questions around my final suggestion.

I like your addition of the "variable accepts dictionary and strings", but for purposes of people scanning and looking at the variables, I think it is best to be consistent with how they should declare the variables.

2022-11-23 03:27 UTC, fivetran-joemarkiewicz commented on README.md
> +    - metadata_field_6
```suggestion
vars: 
  stripe__charge_metadata:
    - name: metadata_field_1
  stripe__invoice_metadata: 
    - name: metadata_field_2
  stripe__payment_intent_metadata:
    - name: incompatible.field
      alias: rename_incompatible_field
  stripe__payment_method_metadata:
    - name: field_is_reserved_word
      alias: field_is_reserved_word_xyz
  stripe__payout_metadata:
    - name: 123
      alias: one_two_three
  stripe__plan_metadata:
    - name: rename
    - alias: renamed_field
  stripe__refund_metadata:
    - name: metadata_field_3
    - name: metadata_field_4
  stripe__subscription_metadata:
    - name: metadata_field_5
  stripe__customer_metadata:
    - name: metadata_field_6
```

2022-11-28 17:26 UTC, merged