union_feature
fivetran/dbt_stripe pull request #54
Opened 2022-12-05 17:39 UTC by fivetran-reneeli

**Are you a current Fivetran customer?** 

Internal
**What change(s) does this PR introduce?** 

Bring the source relation column downstream from the addition of the union feature
**Did you update the CHANGELOG?** 

- [x] Yes

**Does this PR introduce a breaking change?**

- [x] Yes (please provide breaking change details below.)
- [ ] No  (please provide an explanation as to how the change is non-breaking below.)
Will need to refresh for this new field
**Did you update the dbt_project.yml files with the version upgrade (please leverage standard semantic versioning)? (In both your main project and integration_tests)** 

- [x] Yes

**Is this PR in response to a previously created Bug or Feature Request**

- [ ] Yes, Issue/Feature [link bug/feature number here]
- [x] No 

**How did you test the PR changes?** 

 

- [x] BuildKite  
- [ ] Local (please provide additional testing details below)

**Select which warehouse(s) were used to test the PR**
 

- [x] BigQuery
- [x] Redshift
- [x] Snowflake
- [x] Postgres
- [x] Databricks
- [ ] Other (provide details below)

**Provide an emoji that best describes your current mood**
 
:dancer:

**Feedback**

We are so excited you decided to contribute to the Fivetran community dbt package! We continue to work to improve the packages and would greatly appreciate your [feedback](https://www.surveymonkey.com/r/DQ7K7WW) on our existing dbt packages or what you'd like to see next.

2022-12-08 17:04 UTC, fivetran-reneeli commented
@fivetran-jamie  so this is ready for review save for the error on databricks which i think is related to how i added null to price_id and plan_id for the opposite tables as additional field, to help the unique tests pass in the `stg_stripe__pricing`. So I'm still thinking through how to go about this

2022-12-12 20:15 UTC, fivetran-jamie requested changes
looks great! left some comments but nothing too big

2022-12-12 20:15 UTC, fivetran-jamie commented on models/stripe__balance_transactions.sql
> +{% if var('stripe__using_payment_method', True) %}
idk how the syntax in jinja exactly works but basically this logically 
```suggestion
{% if var('stripe__using_payment_method', 'using_payment_method', True) %}
```

2022-12-12 20:15 UTC, fivetran-jamie commented on models/stripe__subscription_details.sql
> +  subscription.start_date_at,
- reminder to update the docs for this column (and add `source_relation` to the docs), unless there's a gonna be a documentation PR later? if not, will also wanna add the union feature to the README

2022-12-12 20:15 UTC, fivetran-jamie commented on models/stripe__invoice_line_items.sql
> +    {% if var('stripe__price', does_table_exist('price')) %}
should we use this `does_table_exist` macro in other places?

2022-12-12 20:15 UTC, fivetran-jamie commented on CHANGELOG.md
> +[#54](https://github.com/fivetran/dbt_stripe/pull/54)
should we add the union feature here or will that be a later PR?

2022-12-12 20:15 UTC, fivetran-jamie commented on CHANGELOG.md
> +[#54](https://github.com/fivetran/dbt_stripe/pull/54)
will also wanna note the column name change in the subscription details model

2022-12-12 20:15 UTC, fivetran-jamie commented on models/stripe__subscription_details.sql
> +  subscription.start_date_at,
also is this like a timestamp? if so maybe it should be `start_at`, otherwise, if its a date, maybe we should leave it as `start_date`? or `start_on`?

2022-12-12 20:28 UTC, fivetran-jamie commented on macros/does_table_exist.sql
> +{%- macro does_table_exist(table_name) -%}
should we move this to fivetran utils?

2022-12-12 23:11 UTC, fivetran-jamie commented on dbt_project.yml
>      subscription: "{{ ref('stg_stripe__subscription') }}"
does `stripe__price` need to be here as well? also, should it match the other vars (so like `stripe__using_price`)

2022-12-13 20:07 UTC, fivetran-reneeli commented on dbt_project.yml
>      subscription: "{{ ref('stg_stripe__subscription') }}"
Good point, the default is true, but it doesn't hurt to explicitly show it, updated

2022-12-14 22:24 UTC, fivetran-jamie approved these changes
looks pretty good to me! just spotted a couple of places where we need to update the price variable name (though i suppose this will be merged with the other PR where you already did that 🤷 )

2022-12-14 22:24 UTC, fivetran-jamie commented on .buildkite/scripts/run_models.sh
> +dbt run --vars '{stripe__using_invoices: false, stripe__using_payment_method: false, stripe__using_subscriptions: false, stripe_timezone: "America/New_York", stripe__subscription_history: true, strip
```suggestion
dbt run --vars '{stripe__using_invoices: false, stripe__using_payment_method: false, stripe__using_subscriptions: false, stripe_timezone: "America/New_York", stripe__subscription_history: true, stripe__using_price: false}' --target "$db"
```

2022-12-14 22:24 UTC, fivetran-jamie commented on models/stripe__invoice_line_items.sql
> +    {% if var('stripe__price', does_table_exist('price')) %}
```suggestion
    {% if var('stripe__using_price', does_table_exist('price')) %}
```

2022-12-14 22:24 UTC, fivetran-jamie commented on models/stripe__invoice_line_items.sql
> +    {% if var('stripe__price', does_table_exist('price')) %}
```suggestion
    {% if var('stripe__using_price', does_table_exist('price')) %}
```

2022-12-15 08:54 UTC, fivetran-reneeli commented
> looks pretty good to me! just spotted a couple of places where we need to update the price variable name (though i suppose this will be merged with the other PR where you already did that 🤷 )

Thanks @fivetran-jamie yeah it doesn't hurt, I added your changes in 👍

2022-12-16 16:41 UTC, merged