start of account daily overview
fivetran/dbt_stripe pull request #55
Opened 2022-12-06 04:22 UTC by fivetran-reneeli

**Are you a current Fivetran customer?** 

Internal
**What change(s) does this PR introduce?** 

Add new models `stripe__invoice details` and `stripe__account daily overview` 

**Did you update the CHANGELOG?** 

- [x] Yes

**Does this PR introduce a breaking change?**

- [] Yes (please provide breaking change details below.)
- [x] No  (please provide an explanation as to how the change is non-breaking below.)

**Did you update the dbt_project.yml files with the version upgrade (please leverage standard semantic versioning)? (In both your main project and integration_tests)** 

- [ ] Yes
Updated in union_feature branch

**Is this PR in response to a previously created Bug or Feature Request**

- [ ] Yes, Issue/Feature [link bug/feature number here]
- [x] No 

**How did you test the PR changes?** 

 

- [x] BuildKite  
- [ ] Local (please provide additional testing details below)

**Select which warehouse(s) were used to test the PR**
 

- [x] BigQuery
- [x] Redshift
- [x] Snowflake
- [x] Postgres
- [x] Databricks
- [x] Other (provide details below)

**Provide an emoji that best describes your current mood**
 
:dancer:

**Feedback**

We are so excited you decided to contribute to the Fivetran community dbt package! We continue to work to improve the packages and would greatly appreciate your [feedback](https://www.surveymonkey.com/r/DQ7K7WW) on our existing dbt packages or what you'd like to see next.

2022-12-12 18:20 UTC, fivetran-reneeli commented
Note on `stripe__subscription_line_items`
- For `stripe__subscription_line_items` I was thinking of just deleting this model since it's just taking invoice data and filtering for just those with a subscription id, so it's not that useful for customers. Further more we already have a `stripe__subscription_details` model.

2022-12-12 23:26 UTC, fivetran-jamie requested changes
looks pretty good! left some in-line Qs

2022-12-12 23:26 UTC, fivetran-jamie commented on README.md
> +    stripe__price: false #  If true, will look `price ` table. If false, will look for the `plan` table.
should it be stripe__using_price? also it should be scoped in `stripe` and `stripe_source` (or just locally)

2022-12-12 23:26 UTC, fivetran-jamie commented on models/stripe__invoice_line_items.sql
> +{% if var('stripe__using_subscriptions', True) %}
is this supposed to be `stripe__using_subscriptions` or `stripe__price`?

2022-12-12 23:26 UTC, fivetran-jamie commented on models/stripe__invoice_line_items.sql
> +left join pricing
should the pricing logic all live within the if block?

2022-12-14 07:18 UTC, fivetran-reneeli commented on README.md
> +This package takes into consideration that not every Stripe account utilizes the `invoice`, `invoice_line_item`, `payment_method`, `payment_method_card`, `plan`, `price`, or `subscription` features,
Good call out, updated

2022-12-14 07:22 UTC, fivetran-reneeli commented on README.md
> +For Stripe connectors set up after February 09, 2022 the `subscription` table has been replaced with the new `subscription_history` table. By default this package will look for your subscription data
updated

2022-12-14 07:23 UTC, fivetran-reneeli commented on models/intermediate/int_stripe__account_daily.sql
> +left join daily_failed_charges
yes good reminder! will leave this open for now. Yeah will need to merge union feature first

2022-12-14 07:27 UTC, fivetran-reneeli commented on models/intermediate/int_stripe__date_spine.sql
> +    {% if run_query(current_date_query).columns[0][0]|string < run_query(last_date_query).columns[0][0]|string %}
that's a good question. I think logically `current_date` should always be more recent that the `last date`, though the exception I can think of is if the balance transaction table has upcoming charges that are in the future. I don't think it hurts to leave this in though?

2022-12-14 07:38 UTC, fivetran-reneeli commented on models/stripe__account_daily_overview.sql
> +        *,
trying this!

2022-12-14 07:39 UTC, fivetran-reneeli commented on README.md
> +    stripe__price: false #  If true, will look `price ` table. If false, will look for the `plan` table.
updated!

2022-12-14 07:40 UTC, fivetran-reneeli commented on models/stripe__invoice_line_items.sql
> +{% if var('stripe__using_subscriptions', True) %}
updated

2022-12-14 07:48 UTC, fivetran-reneeli commented on models/stripe__invoice_line_items.sql
> +left join pricing
Hmm, I think it's fine leaving source_relation out of the block because it's just dependent on the `stripe__using_subscriptions` portion. The `stripe__using_price` is just there to check whether to join on plan_id or price_id. But either way a `pricing` model will exist as long as stripe__using_subscriptions is true. Let me know if that doesn't make sense though

2022-12-14 22:05 UTC, fivetran-jamie commented on models/stripe__invoice_line_items.sql
> +left join pricing
ah i missed the `stripe__using_subscriptions` line, makes sense!

2022-12-14 22:15 UTC, fivetran-jamie commented
looks good to me! only addition i'd make is to the changelog -- maybe add the code for how they could essentially recreate the deleted `stripe__subscription_line_items` model

2022-12-14 22:15 UTC, fivetran-jamie approved these changes

2022-12-14 22:19 UTC, fivetran-jamie commented on .buildkite/scripts/run_models.sh
> +dbt run --vars '{stripe__using_invoices: false, stripe__using_payment_method: false, stripe__using_subscriptions: false, stripe_timezone: "America/New_York", stripe__using_subscription_history: false
```suggestion
dbt run --vars '{stripe__using_invoices: false, stripe__using_payment_method: false, stripe__using_subscriptions: false, stripe_timezone: "America/New_York", stripe__using_subscription_history: false, stripe__using_price: false}' --target "$db"
```

2022-12-16 12:04 UTC, merged