Feature/stripe updates q4 2022
fivetran/dbt_stripe pull request #56
Opened 2022-12-16 16:47 UTC by fivetran-reneeli

**Are you a current Fivetran customer?** 

Internal
**What change(s) does this PR introduce?** 

Incoming stripe updates include the following:

- Bring the source relation column downstream from the addition of the union feature
- Downstream changes from introducing the `pricing` source table which may replace the plan table depending on whether customer migrated to the Price API (some column names have changed in `stripe__invoice_line_items`)
- prefix variables with "stripe__" so they may be used globally
- Add new models `stripe__invoice_details` and `stripe__account_daily_overview`
- Update `stripe__invoice_line_items` with pricing data and `subscription_item_id`
- Remove the `stripe__subscription_line_items` model

For more info see PRs #54 and #55 

**Did you update the CHANGELOG?** 

- [x] Yes

**Does this PR introduce a breaking change?**

-  [x] Yes (please provide breaking change details below.)
- [ ] No  (please provide an explanation as to how the change is non-breaking below.)

**Did you update the dbt_project.yml files with the version upgrade (please leverage standard semantic versioning)? (In both your main project and integration_tests)** 

- [x] Yes

**Is this PR in response to a previously created Bug or Feature Request**

- [ ] Yes, Issue/Feature [link bug/feature number here]
- [x] No 

**How did you test the PR changes?** 

 

- [x] BuildKite  
- [ ] Local (please provide additional testing details below)

**Select which warehouse(s) were used to test the PR**
 

- [x] BigQuery
- [x] Redshift
- [x] Snowflake
- [x] Postgres
- [x] Databricks
- [ ] Other (provide details below)

**Provide an emoji that best describes your current mood**
 
:dancer:

**Feedback**

We are so excited you decided to contribute to the Fivetran community dbt package! We continue to work to improve the packages and would greatly appreciate your [feedback](https://www.surveymonkey.com/r/DQ7K7WW) on our existing dbt packages or what you'd like to see next.

2023-01-12 20:29 UTC, fivetran-joemarkiewicz requested changes
@fivetran-reneeli thanks for working through all of these changes! I have a few comments, questions, and suggestions highlighted below. Let me know if you have any questions.

One larger question I wanted to pose was that the current build of the `stripe__account_daily_overview` model is a bit broken for our data as we have not linked our transactions to our account. I imagine this may be the case for a large number of customers that only have one active account in their stripe instance. Can we work through a solution that essentially creates and links an artificial account_id to the balance transactions **only if** there is one account in the source and the connected account_ids are null.

It looks like we took a somewhat similar approach with the initial build of this package in the daily, weekly, monthly, and quarterly models but simply omitting the account altogether. We should take a similar approach if there is only one account and it is not linked to all transactions. Happy to chat more about this if needed.

2023-01-12 20:29 UTC, fivetran-joemarkiewicz commented on models/stripe__balance_transactions.sql
> +    coalesce(balance_transaction.connected_account_id, charge.connected_account_id) as account_id,
With our data these are always `null`. Let's discuss a workaround for when the connected_account_id's are null

2023-01-12 20:29 UTC, fivetran-joemarkiewicz commented on models/stripe__invoice_details.sql
> +
Small whitespace edit
```suggestion
```

2023-01-12 20:29 UTC, fivetran-joemarkiewicz commented on models/stripe__invoice_line_items.sql
> +{{ config(enabled=var('stripe__using_invoices', True)) }}
What are your thoughts on renaming this model to `stripe__invoice_line_item_details` to be consistend with our other naming conventions this package's models?

2023-01-12 20:29 UTC, fivetran-joemarkiewicz commented on models/stripe__daily_overview.sql
It looks like a lot of what we are doing in this model ends up being done again within the new `stripe__account_daily_overview` model. What are your thoughts on consolidating the logic and referencing the new model as opposed to the balance transaction model again?

2023-01-12 20:29 UTC, fivetran-joemarkiewicz commented on models/stripe__daily_overview.sql
We will need to correct the issue the model experiences when there is no connected account_id, but once we solve that, this should be a feasible consolidation.

2023-01-12 20:29 UTC, fivetran-joemarkiewicz commented on models/intermediate/int_stripe__account_daily.sql
> +    left join date_spine
Should these be switched?

2023-01-12 20:29 UTC, fivetran-joemarkiewicz commented on models/intermediate/int_stripe__account_daily.sql
> +    left join date_spine
When testing this model I see there is only one record. Shouldn't it be the case where this has a record for each day?

2023-01-12 20:29 UTC, fivetran-joemarkiewicz commented on macros/does_table_exist.sql
> +{%- endmacro -%}
It doesn't look like it is used anywhere in the transformation package.

2023-01-12 20:29 UTC, fivetran-joemarkiewicz commented on models/stripe__invoice_details.sql
> +        sum(quantity) as total_quantity
Can we coalesce these to 0? It reads a bit confusing that if an invoice has no line items then it is just `null`. Open to your input here though as that also may be confusing.

2023-01-12 20:29 UTC, fivetran-joemarkiewicz commented on models/stripe__invoice_details.sql
> +    invoice.attempt_count,
Can we coalesce these all to 0

2023-01-12 20:29 UTC, fivetran-joemarkiewicz commented on models/stripe__invoice_line_items.sql
> +    invoice_details.total as invoice_total,
Can we coalesce these to 0

2023-01-20 17:18 UTC, fivetran-reneeli commented on README.md
> +## (Optional) Step 8: Additional configurations
updated

2023-01-20 17:31 UTC, fivetran-reneeli commented on macros/does_table_exist.sql
> +{%- endmacro -%}
It's used in what's currently called `stripe__invoice_line_items`, but yeah, that's true, if it's just in the source package. I'll remove!

2023-01-20 22:39 UTC, fivetran-reneeli commented
Reminder to 

- [ ] 1. regen docs
- [ ] 2. check docs
- [ ] 3. change package deps

2023-01-24 17:23 UTC, fivetran-joemarkiewicz commented on README.md
> +| [stripe__account_daily_overview](https://fivetran.github.io/dbt_stripe/#!/model/model.stripe.stripe__invoice_line_items)      | Each record represents, per account per day, a summary of daily total
Thanks for adding the MRR context.

Additionally, the link for the `stripe__account_daily_overview` looks to be pointing to the `stripe__invoice_line_items` model. Would you be able to update this as well.

2023-01-24 17:36 UTC, fivetran-joemarkiewicz commented on models/stripe.yml
> +  - name: stripe__account_daily_overview
It doesn't look like the the date_index field was added to the documentation

2023-01-24 17:37 UTC, fivetran-joemarkiewicz commented on README.md
> +| [stripe__account_daily_overview](https://fivetran.github.io/dbt_stripe/#!/model/model.stripe.stripe__invoice_line_items)      | Each record represents, per account per day, a summary of daily total
Also, was this model renamed? It looks like it is now `stripe__daily_overview`? I think it is still relevant to keep it named the account_daily_overview. What are your thoughts?

2023-01-24 17:38 UTC, fivetran-joemarkiewicz commented on models/stripe.yml
> +        description: "{{ doc('source_relation') }}"
It doesn't look like a test was added to this model. Can we add it.

2023-01-24 17:41 UTC, fivetran-joemarkiewicz commented on models/stripe.yml
>    - name: stripe__daily_overview
Thanks for adding the source_relation field to the models. However, can we also add them to the docs for these models.

2023-01-24 17:44 UTC, fivetran-joemarkiewicz commented on models/stripe.yml
>        - name: number
I think with other updates to the stripy.yml model this suggestion got lost in the fray. This was originally for the invoice_line_items model. However, with the rename to invoice_details it is still applicable since we rename `number` to `invoice_number`. Would you be able to apply this update to the docs.

2023-01-24 17:45 UTC, fivetran-joemarkiewicz commented on models/stripe.yml
> +  - name: stripe__invoice_line_items
This comment is still applicable to the renamed `stripe__subscription_details` model. Would you be able to add the definitions of both (or either) of these id fields.

2023-01-24 17:46 UTC, fivetran-joemarkiewicz commented on models/intermediate/int_stripe__account_daily.sql
> +        end as date
@fivetran-reneeli would you be able to add more context here? It most likely is correct, but I just want to understand it a bit better.

2023-01-24 17:50 UTC, fivetran-joemarkiewicz commented on models/intermediate/int_stripe__account_daily.sql
> +    daily_account_balance_transactions.total_daily_adjustments_count,
It looks like only a number of these fields were updated to coalesce to 0. Is there a reason the others were not updated?

2023-01-24 17:51 UTC, fivetran-joemarkiewicz commented on models/intermediate/int_stripe__account_daily.sql
> +    daily_account_balance_transactions.daily_net_activity_amount/100.0 as daily_net_activity_amount,
Following our conversation yesterday, these make more sense to me now and as the documentation has been updated, I feel this has been addressed.

2023-01-24 17:51 UTC, fivetran-joemarkiewicz commented on models/intermediate/int_stripe__account_daily.sql
> +    daily_account_balance_transactions.total_daily_net_transactions_amount/100.0 as total_daily_net_transactions_amount,
Same comment as the other. Closing this out.

2023-01-24 18:00 UTC, fivetran-joemarkiewicz commented on models/stripe.yml
> +            - source_relation
I am still seeing a failure on this model. Are there true duplicates here or are we testing on the wrong fields?

2023-01-24 18:14 UTC, fivetran-joemarkiewicz requested changes
@fivetran-reneeli I have a few comments from the previous review that were not addressed and also a few that I added a bit more to my response. Would you be able to review all the previous review comments that have not been resolved and add updates or your comments.

Additionally, I have a few other comments from this review that you can see below. Let me know if you have any questions.

2023-01-24 18:14 UTC, fivetran-joemarkiewicz commented on models/stripe.yml
> +            - source_relation
This test is failing for me. Do you have an understanding why this test may be failing?

![image](https://user-images.githubusercontent.com/74217849/214372282-0c3f0321-1025-4048-8d72-440f19606625.png)

2023-01-24 18:14 UTC, fivetran-joemarkiewicz commented on README.md
> +    stripe_union_databases: ['stripe_db_1','stripe_db_2'] # use this if the data is in different databases/projects but uses the same schema name
Is there a reason there are duplicates of steps 6 and 7? Additionally, I feel both of these may fall under the optional configurations and are not necessarily required steps.

2023-01-26 23:27 UTC, fivetran-joemarkiewicz requested changes
@fivetran-reneeli a few more comments, but we are getting close!

Additionally, I noticed the .DS_Store file is in this repo. Would you mind removing that since it is not technically necessary.

2023-01-26 23:27 UTC, fivetran-joemarkiewicz commented on models/stripe.yml
> +  - name: stripe__invoice_line_items
Let's still include both of these in the end model.

2023-01-26 23:27 UTC, fivetran-joemarkiewicz commented on models/intermediate/int_stripe__account_daily.sql
> +        end as date
@fivetran-reneeli bumping this question

2023-01-26 23:27 UTC, fivetran-joemarkiewicz commented on models/stripe__invoice_line_item_details.sql
> +    and invoice_line_item.source_relation = pricing.source_relation
Reminder to update here based on our conversation

2023-01-26 23:33 UTC, fivetran-joemarkiewicz commented on models/stripe.yml
> +            - source_relation
This test is currently failing for me. Looking at our previous build it turns out we did not want a test here since there could in fact be multiple customers (especially if they are not associated with a customer_id). Let's remove this test.

My apologies for requesting it to go in.

2023-01-27 18:10 UTC, fivetran-reneeli commented on models/stripe__invoice_line_item_details.sql
> +    and invoice_line_item.source_relation = pricing.source_relation
updated

2023-01-27 18:10 UTC, fivetran-reneeli commented on models/stripe__customer_overview.sql
> -      {% endif %}
added back in

2023-01-27 18:10 UTC, fivetran-reneeli commented on models/stripe__customer_overview.sql
> -      {% endif %}
added

2023-01-27 18:10 UTC, fivetran-reneeli commented on models/stripe.yml
> +            - source_relation
All good, I forgot about the potential missing customer id scenario-- removed the test

2023-01-30 16:18 UTC, fivetran-joemarkiewicz requested changes
@fivetran-reneeli thanks for making all the changes I requested and responding to my questions.

I believe this will be the last review where I request changes! I have a few comments and requests in my review. Additionally, please apply the same CHANGELOG and README updates from the source review into this one.

Finally, the biggest request I have is to address the issue in the daily_overview model where the weekends (days without transactions) are showing as `null`. We have a good roadmap in Recurly on how to address this issue. Let me know if you would like for me to elaborate more on this piece.

2023-01-30 16:18 UTC, fivetran-joemarkiewicz commented on models/stripe__daily_overview.sql
> +        round(account_rolling_totals.{{ t }},2) as {{ t }},
Can we coalesce this field

2023-01-30 16:18 UTC, fivetran-joemarkiewicz commented on models/stripe__daily_overview.sql
> +{% set total_fields =  ['total_daily_sales_amount', 'total_daily_refunds_amount', 'total_daily_adjustments_amount', 'total_daily_other_transactions_amount', 'total_daily_gross_transaction_amount', 't
If you look at the data generated from this model, we have missing values on days where there are no transactions. You can see this is most evident on weekends. You will notice all the fields are `null`.

For these, the total_daily fields should be 0 instead of `null` and the `rolling_total` fields should roll up the previous days totals. See how we did this within Recurly.
- [First](https://github.com/fivetran/dbt_recurly/blob/2da1316991d1498e85317150d2587c74ea358972/models/intermediate/int_recurly__account_rolling_totals.sql#L48-L53) we generate the rolling totals for dates with transactions. 
- [Second](https://github.com/fivetran/dbt_recurly/blob/2da1316991d1498e85317150d2587c74ea358972/models/intermediate/int_recurly__account_partitions.sql#L14-L20), we generate the partition of these days
- [Then lastly](https://github.com/fivetran/dbt_recurly/blob/2da1316991d1498e85317150d2587c74ea358972/models/intermediate/int_recurly__account_running_totals.sql#L41-L54) we generate the running totals and coalesce any of the daily fields to be 0 if null.

We are going to need to repurpose this logic within the stripe models.

2023-01-30 18:31 UTC, fivetran-reneeli commented on models/stripe__customer_overview.sql
> +        customer.{{ fivetran_utils.pivot_json_extract(string = 'metadata', list_of_properties = var('stripe__customer_metadata')) }},
Oh I see what this does, it takes all the columns we'd be bringing in from the customer staging model excluding the ones that are already in the select statement. Yes I will try this!

2023-01-30 20:06 UTC, fivetran-reneeli commented on models/stripe__daily_overview.sql
> +        round(account_rolling_totals.{{ t }},2) as {{ t }},
This has been moved to an int model called `int_stripe__account_rolling_totals` so the coalesce will be in there!

2023-01-30 20:08 UTC, fivetran-reneeli commented on models/stripe__daily_overview.sql
> +{% set total_fields =  ['total_daily_sales_amount', 'total_daily_refunds_amount', 'total_daily_adjustments_amount', 'total_daily_other_transactions_amount', 'total_daily_gross_transaction_amount', 't
Hi Joe, just updated everything following this. Appreciate you detailing the steps! The changes I made are very similar and I have separated the previous daily overview model into `int_stripe__account_rolling_totals`, `int_stripe__account_partitions` and `stripe__daily_overview`.  Note that I did the coalesce(x, 0) and rounding in the int models so I left it out of the final model, and I see it persisting when checking, but lmk if you think we should bring it down as well.

2023-01-30 20:40 UTC, fivetran-reneeli commented
- [ ] docs regen 
- [ ] change package deps

2023-01-30 21:43 UTC, fivetran-joemarkiewicz approved these changes
@fivetran-reneeli thanks for making those final updates! After reviewing, this looks ready to go! I just have a few super minor comments and suggestions, but otherwise this is good to ship!

2023-01-30 21:43 UTC, fivetran-joemarkiewicz commented on CHANGELOG.md
> +| using_price | stripe__using_price
Can you also include the name change for the stripe__plan_metadata variable

2023-01-30 21:43 UTC, fivetran-joemarkiewicz commented on models/intermediate/int_stripe__account_daily.sql
> +        balance_transaction.source_relation,
This field is showing as null for the days without transactions. To be consistent, let's use the date_spine source_relation field. Let me know if you have any concerns with this suggestion.
```suggestion
        date_spine.source_relation,
```

2023-01-30 21:43 UTC, fivetran-joemarkiewicz commented on packages.yml
> +  warn-unpinned: false
Reminder to switch before release

2023-01-30 21:43 UTC, fivetran-joemarkiewicz commented on packages.yml
> +#   version: [">=0.8.0", "<0.9.0"]
```suggestion
# - package: fivetran/stripe_source
#   version: [">=0.9.0", "<0.10.0"]
```

2023-01-31 02:56 UTC, fivetran-reneeli commented on CHANGELOG.md
> +| using_price | stripe__using_price
Added-- mentioned in its own bullet point since these rows are just for variables that have been prefixed with stripe__

2023-01-31 02:57 UTC, fivetran-reneeli commented on models/intermediate/int_stripe__account_daily.sql
> +        balance_transaction.source_relation,
Ooh good catch, updated

2023-01-31 03:02 UTC, fivetran-reneeli commented on packages.yml
> +#   version: [">=0.8.0", "<0.9.0"]
updated

2023-01-31 03:23 UTC, merged