Feature/q3 2023 updates
fivetran/dbt_stripe pull request #69
Opened 2023-08-31 20:53 UTC by fivetran-reneeli

## PR Overview
**This PR will address the following Issue/Feature:** n/a

**This PR will result in the following new package version:**

Significant updates to our Stripe package for Q3 2023. 

**Please detail what change(s) this PR introduces and any additional information that should be known during the review of this PR:**

- Addition of new Stripe report end models, plus updates to the balance transaction model
- Additional of new fields 

## PR Checklist
### Basic Validation
Please acknowledge that you have successfully performed the following commands locally:
- [x] dbt compile
- [x] dbt run –full-refresh
- [x] dbt run
- [x] dbt test
- [x] dbt run –vars (if applicable)

Before marking this PR as "ready for review" the following have been applied:
- [n/a] The appropriate issue has been linked and tagged
- [x] You are assigned to the corresponding issue and this PR
- [x] BuildKite integration tests are passing

### Detailed Validation
Please acknowledge that the following validation checks have been performed prior to marking this PR as "ready for review":
- [x] You have validated these changes and assure this PR will address the respective Issue/Feature.
- [x] You are reasonably confident these changes will not impact any other components of this package or any dependent packages.
- [x] You have provided details below around the validation steps performed to gain confidence in these changes.

Confirm that these additions appear in the target schema when run

### Standard Updates
Please acknowledge that your PR contains the following standard updates:
- Package versioning has been appropriately indexed in the following locations:
    - [x] indexed within dbt_project.yml
    - [x] indexed within integration_tests/dbt_project.yml
- [x] CHANGELOG has individual entries for each respective change in this PR
    
- [n/a] README updates have been applied (if applicable)
    
- [x] DECISIONLOG updates have been updated (if applicable)
- [x] Appropriate yml documentation has been added (if applicable)

### dbt Docs
Please acknowledge that after the above were all completed the below were applied to your branch:
- [ ] docs were regenerated (unless this PR does not include any code or yml updates)

### If you had to summarize this PR in an emoji, which would it be?
 
:dancer:

2023-10-13 16:28 UTC, fivetran-joemarkiewicz requested changes
@fivetran-reneeli thanks for working through these changes. It seems that the most significant updates have been made to the balance transactions model which I can see being valuable to all users, not just the ones who will take advantage of these new reports!

I do have a number of requests for you to review and make appropriate updates. Some major ones include my thoughts of renaming the fields in the staging models as opposed to the end model for consistency and allowing the focus of the transform models to be used for transformation purposes and not renaming. This also follows our intention of the source package. Additionally, I wonder if we can consolidate the payout enhanced model with the balance transaction since they are almost identical. I would like to discuss those two in more detail before you move forward with updates. 

See my other comments below and let me know if you have any questions. Thanks!

2023-10-13 16:28 UTC, fivetran-joemarkiewicz commented on models/stripe_reports/stripe__activity_itemized_2.sql
> +    balance_transaction_amount as amount,
Why do we rename `reporting_category` to `balance_transaction_reporting_category`, but then we rename `balance_transaction_currency` to `currency` and then the same for amount? We should choose a pattern and then stick to that. Which do pattern do you feel is best to stick with for this model?

2023-10-13 16:28 UTC, fivetran-joemarkiewicz commented on models/stripe_reports/stripe__balance_change_from_activity_itemized_3.sql
> +    balance_transaction_net as net,
It looks like we have a consistent pattern here. Maybe we should use this type of pattern in all of these new models. Thoughts?

2023-10-13 16:28 UTC, fivetran-joemarkiewicz commented on models/stripe_reports/stripe__payout_itemized_3.sql
> +    end as effective_at,
Request to reform case statement to be in line with our [style guidelines](https://github.com/fivetran/dbt_style_guide/blob/main/sql_guidelines.md).
```suggestion
    case 
        when is_automatic = true then payout_arrival_date_at 
        else payout_created_at
    end as effective_at,
```

2023-10-13 16:28 UTC, fivetran-joemarkiewicz commented on packages.yml
> +      warn-unpinned: false
Reminder to switch before merge.

2023-10-13 16:28 UTC, fivetran-joemarkiewicz commented on models/stripe.yml
> +    columns:
It looks like there are a few fields documented but not brought through with all variables enabled. Should these still be here?
![image](https://github.com/fivetran/dbt_stripe/assets/74217849/e5e552b7-f82e-4db9-b096-d0783809cccc)

2023-10-13 16:28 UTC, fivetran-joemarkiewicz commented on models/stripe.yml
> +    columns:
It looks like there are a few fields documented but not used when all variables are set to true. Are these still needed or are they not being brought through and need to be updated?

![image](https://github.com/fivetran/dbt_stripe/assets/74217849/cb44ab33-f212-4826-9f27-84f5078dc739)

2023-10-13 16:28 UTC, fivetran-joemarkiewicz commented on models/stripe.yml
> +    columns:
It looks like there are a few fields not documented and some documented but not used. Can you update accordingly.

![image](https://github.com/fivetran/dbt_stripe/assets/74217849/e006d4ad-bcb8-439b-be75-eeeb718a5210)

2023-10-13 16:28 UTC, fivetran-joemarkiewicz commented on models/stripe.yml
> +    columns:
It looks like `payout_description` is documented but not brought through. Is this intentional?

![image](https://github.com/fivetran/dbt_stripe/assets/74217849/9abd6426-ab34-47b5-86a8-df4e1b5f58fd)

2023-10-13 16:28 UTC, fivetran-joemarkiewicz commented on models/stripe__balance_transactions.sql
> +select
Finally, there do seem to be quite a few new fields or updated names that need to be properly documented in the yml.

2023-10-13 17:18 UTC, fivetran-joemarkiewicz commented on models/stripe__balance_transactions.sql
> +        company_name as account_name,
Is this true?

2023-10-13 20:44 UTC, fivetran-reneeli commented on models/stripe__balance_transactions.sql
> +    balance_transaction.source_id,
I excluded this one since the `balance_transactions` is the only object containing `source_id`, but I'll rename here for posterity

2023-10-13 20:51 UTC, fivetran-reneeli commented on models/stripe__balance_transactions.sql
> +    coalesce(reporting_category,
Same reason as with `source_id`, I don't believe the other staging models contain reporting_category therefore I didn't prefix it. I don't see any harm in aliasing it though, except in the end reports it'll just be renamed back to just `reporting_category`.

The coalesce is needed because reporting_category should be the default but it may the case not all customers have that field. Actually this is the case in our package, where presently, we are using the `balance_transactions.type` to determine `reporting_category`.  

The case-when logic I created follows this [table](https://stripe.com/docs/reports/reporting-categories) found in the stripe docs

![image](https://github.com/fivetran/dbt_stripe/assets/91097070/1ed7c208-c0bd-4c90-9b59-65f586f3ca3a)

2023-10-13 20:53 UTC, fivetran-reneeli commented on models/stripe_reports/stripe__activity_itemized_2.sql
> +    balance_transaction_amount as amount,
We discussed but just to leave a paper trail--  The renaming may seem arbitrary but it follows verbatim from the Stripe docs

2023-10-13 20:53 UTC, fivetran-reneeli commented on models/stripe_reports/stripe__balance_change_from_activity_itemized_3.sql
> +    balance_transaction_net as net,
Same as above

2023-10-13 21:01 UTC, fivetran-reneeli commented on models/stripe__balance_transactions.sql
> +select
Ah I forgot to update the yml when making the changes to balance_transactions yesterday, yup will do

2023-10-13 21:07 UTC, fivetran-reneeli commented on models/stripe__balance_transactions.sql
> +        company_name as account_name,
Actually, after reviewing the docs I don't think they necessarily the same. Company fields are child attributes to the account object, but I think it'll be safer to keep them to just the company since it's not verified it can be extended to account info.

https://stripe.com/docs/api/accounts/update#update_account-company-name

2023-10-13 21:11 UTC, fivetran-reneeli commented on models/stripe.yml
> +    description: Each record provides additional details on each balance_transaction.
done

2023-10-13 21:12 UTC, fivetran-reneeli commented on models/stripe__balance_transactions.sql
> +    (select
done

2023-10-13 21:15 UTC, fivetran-reneeli commented on models/intermediate/int_stripe__payout_enhanced.sql
> +left join balance_transaction
Hi Joe, after looking into it again I think your point is right, that each payout will always be associated with a `balance_transaction_id`. In that case, I will try doing the payout-based reports off of balance_transactions instead and verify it!

https://stripe.com/docs/api/payouts/object#payout_object-balance_transaction

2023-10-13 22:49 UTC, fivetran-reneeli commented on CHANGELOG.md
> +## Updates:
done

2023-10-16 19:41 UTC, fivetran-reneeli commented on models/intermediate/int_stripe__payout_enhanced.sql
> +left join balance_transaction
Following up, I have verified that the output basing off of the balance transaction objects vs output off the payout object is the same, so I will swap it out and remove the int payouts enhanced model

2023-10-17 14:27 UTC, fivetran-reneeli commented on models/intermediate/int_stripe__payout_enhanced.sql
> +        source_relation
updated to doing a select * in the CTEs and renaming in the final select statement

2023-10-17 14:27 UTC, fivetran-reneeli commented on models/stripe__balance_transactions.sql
> +        source_relation
renamed in final select statement

2023-10-17 14:58 UTC, fivetran-reneeli commented on README.md
> +    version: [">=0.11.0", "<0.12.0"]
updated

2023-10-17 15:19 UTC, fivetran-reneeli commented on models/stripe__balance_transactions.sql
> +    coalesce(reporting_category,
Actually, since reporting category only belongs to the balance transactions object, I'll probably leave it without a prefix

2023-10-17 19:52 UTC, fivetran-reneeli commented on models/stripe.yml
> +    columns:
thanks for catching -- removed

2023-10-17 19:52 UTC, fivetran-reneeli commented on models/stripe.yml
> +    columns:
removed

2023-10-17 19:56 UTC, fivetran-reneeli commented on models/stripe.yml
> +    description: This is modeled after the [titular report](https://stripe.com/docs/reports/payout-reconciliation#schema-ending-balance-reconciliation-itemized-4) from Stripe. This report is related
So now that I have in the CTE a 

`select * from balance_transactions where automatic_payout_id is not null`

this will not populate for customers that don't have this feature enabled and wouldn't require them to manually enable/disable a variable. 

Though it wouldn't hurt setting a variable for this and have the default be true, but I'm wondering if it's redundant.

2023-10-17 19:56 UTC, fivetran-reneeli commented on models/stripe.yml
> +    columns:
updated

2023-10-17 19:58 UTC, fivetran-reneeli commented on models/stripe.yml
> +    columns:
thanks for catching -- it should have been brought through. updated

2023-10-18 15:18 UTC, fivetran-joemarkiewicz commented on models/stripe.yml
> +    description: This is modeled after the [titular report](https://stripe.com/docs/reports/payout-reconciliation#schema-ending-balance-reconciliation-itemized-4) from Stripe. This report is related
Let's plan to leave this for now and not include a variable. Due to our fill column macros we will be able to ensure customers won't see failures for this model if they don't have the feature enabled, but will just see an empty table. I say we keep it as is for right now and we can adjust based off customer reception following release.

2023-10-18 15:21 UTC, fivetran-joemarkiewicz commented on models/stripe__balance_transactions.sql
> +    coalesce(reporting_category,
@fivetran-reneeli can we still add the prefix to the `reporting_category` used in the equation. I understand it is not used in the other ctes being joined in, but for consistency let's add it in.

2023-10-18 15:31 UTC, fivetran-joemarkiewicz commented on CHANGELOG.md
> +| description | balance_transaction_description
Thanks for adding this. However, this is a breaking change. We should put this at the very top with the alarms so customers know these have changed and they need to take this into account.

2023-10-18 15:32 UTC, fivetran-joemarkiewicz commented on README.md
> +| [stripe__payout_itemized_3](https://fivetran.github.io/dbt_stripe/#!/model/model.stripe.stripe__payout_itemized_3)       | Modeled after the [titular report](https://stripe.com/docs/reports/balance
Thanks for adding these in. However, the descriptions are really long for the README. Would you be able to condense these down to follow the brevity of our other model descriptions in the README? This long form description works great for the yml, but not as much for the README.

2023-10-18 16:07 UTC, fivetran-reneeli commented on models/stripe.yml
> +    description: This is modeled after the [titular report](https://stripe.com/docs/reports/payout-reconciliation#schema-ending-balance-reconciliation-itemized-4) from Stripe. This report is related
Yup I'm in agreement with that!

2023-10-18 16:11 UTC, fivetran-reneeli commented on models/stripe__balance_transactions.sql
> +    coalesce(reporting_category,
did the same with `source_id`

2023-10-18 17:21 UTC, fivetran-reneeli commented on CHANGELOG.md
> +- Updated the `stripe__balance_transactions` with the following changes:
updated

2023-10-18 17:43 UTC, fivetran-reneeli commented on README.md
> +| [stripe__payout_itemized_3](https://fivetran.github.io/dbt_stripe/#!/model/model.stripe.stripe__payout_itemized_3)       | Modeled after the [titular report](https://stripe.com/docs/reports/balance
updated!

2023-10-18 19:47 UTC, fivetran-joemarkiewicz approved these changes
Thanks so much for working on these updates @fivetran-reneeli. This looks good to go to release review!

2023-10-18 19:47 UTC, fivetran-joemarkiewicz commented on CHANGELOG.md
> +| source | balance_transaction_source
Sorry that I missed this earlier, but looks like you made this `*_id`.
```suggestion
| source | balance_transaction_source_id
```

2023-10-18 19:47 UTC, fivetran-joemarkiewicz commented on CHANGELOG.md
> +[PR #69](https://github.com/fivetran/dbt_stripe/pull/69) contains the following updates:
Small request to just have the PR ref at the very top
```suggestion
[PR #69](https://github.com/fivetran/dbt_stripe/pull/69) contains the following updates:

## 🚨 Breaking Changes 🚨
```

2023-10-18 19:47 UTC, fivetran-joemarkiewicz commented on packages.yml
> +      warn-unpinned: false
Bumping this reminder before merge

2023-10-18 22:16 UTC, merged