feature/quickstart-yml-addition
fivetran/dbt_stripe pull request #73
Opened 2024-01-16 16:48 UTC by fivetran-joemarkiewicz

Small PR to add quickstart.yml to be properly parsed by the Quickstart automation.

As this is just an addition of the quickstart.yml, there is no need for a new release or version bump.

2024-02-07 21:32 UTC, fivetran-reneeli commented on .quickstart/quickstart.yml
> +    - subscription_history
dont we also need to add
- price
- plan

https://github.com/fivetran/dbt_stripe_source/blob/main/models/tmp/stg_stripe__price_plan_tmp.sql

2024-02-07 21:33 UTC, fivetran-reneeli requested changes
Please see question above!

2024-02-08 14:44 UTC, fivetran-joemarkiewicz commented on .quickstart/quickstart.yml
> +    - subscription_history
Great question and this is a variable I was going back and forth on including or not. Ultimately I did not include this source in the variable config as `price` or `plan` should always be included if the subscription table is present. However, it could be either price or plan. Therefore, if we check to see if both or even just one are present then the variable will likely be set incorrectly. Therefore, omitting this source from the variable would be more appropriate to ensure false failures do not occur.

2024-02-08 15:31 UTC, fivetran-reneeli commented on .quickstart/quickstart.yml
> +    - subscription_history
Ok gotcha, yeah I wasn't sure how quickstart would handle the case where one or the other is required but not both. But that makes sense that one will always be present with the subscription table.

2024-02-08 15:32 UTC, fivetran-reneeli approved these changes
approved

2024-02-08 15:34 UTC, merged