Release/v0.13.0
fivetran/dbt_stripe pull request #78
Opened 2024-05-21 17:32 UTC by fivetran-catfritz

## PR Overview
**This PR will address the following Issue/Feature:**
- #70 
- #77 

**This PR will result in the following new package version:**

- Breaking since the folder `stripe_reports` was renamed to `stripe_financial_reports` and could break if users relied on the old name.

**Please provide the finalized CHANGELOG entry which details the relevant changes included in this PR:**

> ## 🚨 Breaking Changes 🚨
> - Renamed folder `stripe_reports` to `stripe_financial_reports` to be more descriptive of the contents.
>   - ⚠️ If you are using folder names to scope out configs, runs, etc., you will need to update the folder name.
> 
> ## Bug fixes
> - Updated model `int_stripe__date_spine` to accommodate cases when model `stripe__balance_transactions` has no records. 
>   - Previously, the date spine relied on `stripe__balance_transactions` to set date bounds, which caused errors if empty. Now, the model defaults to a one-month range in such cases.
> 
> ## Under the hood
> - Updated structure of model `int_stripe__date_spine` for improved performance and maintainability.

## PR Checklist
### Basic Validation
Please acknowledge that you have successfully performed the following commands locally:
- [x] dbt run –full-refresh && dbt test
- [ ] ~dbt run (if incremental models are present) && dbt test~

Before marking this PR as "ready for review" the following have been applied:
- [x] The appropriate issue has been linked, tagged, and properly assigned
- [x] All necessary documentation and version upgrades have been applied
    
- [x] docs were regenerated (unless this PR does not include any code or yml updates)
  - Will regen after approval.
- [x] BuildKite integration tests are passing
- [x] Detailed validation steps have been provided below

### Detailed Validation
Please share any and all of your validation steps:

- Validation tests pass.

### If you had to summarize this PR in an emoji, which would it be?
 
🍓

2024-05-23 20:05 UTC, fivetran-joemarkiewicz requested changes
@fivetran-catfritz thanks for working on this update! I just have a few comments and suggestions before approving. Let me know if you have any questions regarding my comments. Thanks!

2024-05-23 20:05 UTC, fivetran-joemarkiewicz commented on integration_tests/tests/integrity/integrity_daily_overview.sql
> +    on spine.spine_count != daily_overview.daily_overview_count
Disregard this comment. I couldn't delete it for some reason.

2024-05-23 20:05 UTC, fivetran-joemarkiewicz commented on CHANGELOG.md
> +# dbt_stripe v0.13.0
Be sure to also update the version in the README

2024-05-23 20:15 UTC, fivetran-catfritz commented on models/intermediate/int_stripe__date_spine.sql
> +            ) as max_date
The greatest is to imitate the prior code's line 30. I did take into account that the greatest of a date and null is a null, so that's why there is the coalesce of line 17. If the greatest check produces a null, then it uses the current date. I also made sure to test this by supplying empty source tables.

2024-05-23 20:15 UTC, fivetran-catfritz commented on models/intermediate/int_stripe__date_spine.sql
> +        from {{ ref('stripe__balance_transactions') }}
I didn't this time and followed what was used in the current version since I know in the past when we've done that, someone that was using a custom source had an issue. However, I agree that would make things easier. I am open to use either ref or the source.

2024-05-23 20:15 UTC, fivetran-catfritz commented on CHANGELOG.md
> +# dbt_stripe v0.13.0
Sorry about that. Thanks!

2024-05-23 20:15 UTC, fivetran-catfritz commented on models/intermediate/int_stripe__date_spine.sql
> +        from {{ ref('stripe__balance_transactions') }}
Same consideration as above!

2024-05-23 20:43 UTC, fivetran-joemarkiewicz approved these changes
@fivetran-catfritz thanks for answering my questions! Given the conversations from the comments, this looks good to go!

2024-05-23 20:43 UTC, fivetran-joemarkiewicz commented on models/intermediate/int_stripe__date_spine.sql
> +        from {{ ref('stripe__balance_transactions') }}
You make a good point, and I am unsure what this impact would be for folks using the union feature. It would just pick one source and not take into account all other transactions across the other sources. With that, I say we keep the ref as you have it.

2024-05-23 20:43 UTC, fivetran-joemarkiewicz commented on models/intermediate/int_stripe__date_spine.sql
> +            ) as max_date
Ah yeah I see what you are saying and see how you accounted for this. Great, thanks for sharing the detail behind your code update. Looks good to me!

2024-05-23 20:43 UTC, fivetran-joemarkiewicz commented on models/intermediate/int_stripe__date_spine.sql
> +        from {{ ref('stripe__balance_transactions') }}
No changes required base on the above comment

2024-05-24 17:31 UTC, fivetran-reneeli approved these changes
Looks good!

2024-05-27 23:57 UTC, merged