Feature/normalized billing model
fivetran/dbt_stripe pull request #81
Opened 2024-06-06 15:54 UTC by fivetran-reneeli

to be completed

2024-06-12 15:58 UTC, fivetran-joemarkiewicz requested changes
@fivetran-reneeli please see below for my comments and questions. Additionally, there are a few items that are leaving me a bit puzzled when reviewing the resulting data. I schedule some time for later today to discuss in more detail and determine next steps.

Before we meet, it would be great if you can review the questions and make any necessary changes.

2024-06-12 15:58 UTC, fivetran-joemarkiewicz commented on integration_tests/dbt_project.yml
> +version: '0.13.1'
Request to bump to v0.14.0

2024-06-12 15:58 UTC, fivetran-joemarkiewicz commented on models/common_data_models/stripe__line_item_enhanced.sql
> +    from {{ var('invoice') }} inv
Can we have invoice be brought in with its own cte? For example:
```sql
), invoice as (

    select *
    from {{ var('invoice') }} 

),
```

To be in line with our code formatting standards

2024-06-12 15:58 UTC, fivetran-joemarkiewicz commented on models/common_data_models/stripe__line_item_enhanced.sql
> +        cast(subscription.status as {{ dbt.type_string() }}) as subscription_status,
Even if subscriptions are not used, we will want to include the fields, albeit make sure they are `null`. Can we update this code to populate the fields if the subscriptions variable is true and just use `null` if the subscriptions variable is false

2024-06-12 15:58 UTC, fivetran-joemarkiewicz commented on models/common_data_models/stripe__line_item_enhanced.sql
> +        {% endif %}
Same comment as above

2024-06-13 19:20 UTC, fivetran-reneeli commented on models/common_data_models/stripe__line_item_enhanced.sql
> +        cast(null as {{ dbt.type_string() }}) as customer_level,
Updated

2024-06-13 19:20 UTC, fivetran-reneeli commented on models/common_data_models/stripe__line_item_enhanced.sql
> +    {% endif %}
This has since been updated!

2024-06-13 19:21 UTC, fivetran-reneeli commented on models/common_data_models/stripe__line_item_enhanced.sql
> +        cast(invoice_line_item.quantity as {{ dbt.type_int() }}) as quantity,
Oh good call to be more conservative; I didn't think about the potential of being a non whole number. Updated all int casts to numeric

2024-06-13 19:21 UTC, fivetran-reneeli commented on models/common_data_models/stripe__line_item_enhanced.sql
> +        {% endif %}
Updated

2024-06-13 19:21 UTC, fivetran-reneeli commented on models/common_data_models/stripe__line_item_enhanced.sql
> +        cast(subscription.status as {{ dbt.type_string() }}) as subscription_status,
Oh right, we should still keep the fields. Updated

2024-06-13 19:22 UTC, fivetran-reneeli commented on models/common_data_models/stripe__line_item_enhanced.sql
> +        invoice_line_item_agg.total_quantity
not necessary now that this has been removed

2024-06-13 19:22 UTC, fivetran-reneeli commented on models/common_data_models/stripe__line_item_enhanced.sql
> +    from {{ var('invoice') }} inv
not necessary now that this has been removed

2024-06-13 19:22 UTC, fivetran-reneeli commented on integration_tests/dbt_project.yml
> +version: '0.13.1'
bumped

2024-06-13 19:23 UTC, fivetran-reneeli commented on models/common_data_models/stripe__line_item_enhanced.sql
> +order by header_id, line_item_index
Good point - removed!

2024-06-13 19:24 UTC, fivetran-reneeli commented on models/common_data_models/stripe__line_item_enhanced.sql
> +        cast(price_plan.product_id as {{ dbt.type_string() }}) as product_id, -- The ID of the product this price is associated with. https://docs.stripe.com/api/invoices/line_item#invoice_line_item_
ah yes my bad-- product info should be null at the invoice level

2024-06-13 19:24 UTC, fivetran-reneeli commented on models/common_data_models/stripe__line_item_enhanced.sql
> +        cast(invoice.total as {{ dbt.type_int() }}) as total_amount,
updated since our sync yesterday to correctly display amounts

2024-06-13 19:25 UTC, fivetran-reneeli commented on models/common_data_models/stripe__line_item_enhanced.sql
model has been updated to remove duplicates

2024-06-13 19:25 UTC, fivetran-reneeli commented on models/common_data_models/stripe__line_item_enhanced.sql
> +        cast(null as {{ dbt.type_string() }}) as product_category,
removed

2024-06-14 14:39 UTC, fivetran-reneeli commented on dbt_project.yml
> +version: '0.13.1'
bumped

2024-06-14 16:30 UTC, fivetran-reneeli commented on models/common_data_models/stripe__line_item_enhanced.sql
> +        invoice_id,
Since there can be more than 1 discount per invoice, I summed discounts at the invoice level before joining to invoice

2024-06-18 14:45 UTC, fivetran-joemarkiewicz reviewed
@fivetran-reneeli thanks for making these updates! There were a few final comments I have, but I ended up consolidating and moving the changes to PR #82. This way there is a more clean PR (with less initial review comments) that we can share externally with the community and where they can add their own comments. 

We will like close this out, but please review the [minor changes between the branches](https://github.com/fivetran/dbt_stripe/compare/feature/normalized-billing-model...feature/standardized-billing-line-item-model) to understand the updates I applied.

2024-08-02 20:58 UTC, fivetran-joemarkiewicz commented
Closing this as PR #82 will address this

2024-08-02 20:58 UTC, closed without merging